# Archivo: render.yaml
# Este es el plano que le dice a Render cómo construir y ejecutar tu servicio.

services:
  - type: web
    name: video-ai-backend
    runtime: python
    plan: free
    
    # Comando para instalar todas las dependencias de tu proyecto.
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
      
    # Comando para iniciar el servidor web con Gunicorn.
    startCommand: "gunicorn --worker-tmp-dir /dev/shm app:app"
    
    # Aquí le indicamos a Render que debe buscar las claves secretas
    # en el Grupo de Entorno que creaste en el Paso 2.
    envVarGroups:
      - name: mis-claves-google # ¡IMPORTANTE! Este nombre debe ser idéntico al del grupo que creaste.
    
    # Finalmente, definimos la versión de Python.
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
