services:
  - type: web
    name: video-ai-backend
    runtime: python
    plan: free
    
    # Comandos para construir tu aplicación
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
      
    # Comando para iniciar tu aplicación
    startCommand: "gunicorn --worker-tmp-dir /dev/shm app:app"
    
    # Le decimos al plano que busque las claves en un "Grupo de Entorno"
    envVarGroups:
      - name: mis-claves-google 
    
    # Variables no secretas
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
