services:
  - type: web
    name: backend-ia-videos
    env: python
    region: oregon  # Puedes cambiarlo a 'frankfurt' si estás en Europa
    plan: free  # O usa 'starter' si quieres evitar que se duerma
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        value: tu_api_key_de_google_aqui
      - key: GOOGLE_CLOUD_PROJECT
        value: tu_id_de_proyecto_google_cloud
      - key: GCS_BUCKET_NAME
        value: tu_nombre_de_bucket_gcs
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false  # Lo cargarás de forma segura como secreto desde el panel de Render